### PR TITLE
Add link to repo of lightning talk

### PR DESCRIPTION
**Pull request by Flash0ver**
.NET 6 API diff

### CODE REVIEW

**Comment by Flash0ver** [comment]
I'm not sure if that's the right location and/or format.
I noticed that other meetup notes usually have a dedicated *Links* header. But here I suggest just one - so I belive that would be a bit of an overkill.
As an alternative, we could add 1 or 2 additional links to related resources. But here I'm unsure whether that would unnecessarily "bloat" the page.

**Comment by dracan** [comment]
Could you put it under the bio with a bullet point, so it's consistent with the links in Marc Duiker's entry on the same page?

**Comment by Flash0ver** [comment]
Thanks for your quick feedback. I should have compared the format to `this` page instead 😃.

**Comment by dracan** [comment]
Merged. Thanks again for your awesome talk :)

**Comment by Flash0ver** [comment]
Thank you again for having me! And thanks for this discussion and merge.

**Pull request merged**
